fruits:
    [
        "apple",
        "Plum",
        "orange",
        "cherry",
        "plum",
        "Grapefruit",
        "grapefruit",
        "banana",
        "Pineapple",
        "strawberry",
        "Loquat",
        "Red Heart Dragon Fruit",
        "fruit of life",
        "Mare's Milk Grape",
        "watermelon",
        "pear",
    ]
colors: ["Red", "Yellow", "Green", "White", "Orange", "Purple"]
